Repository Textualize/trogon, pull requests merged in 2024-09, with the labels that each got.

#74 Fix typo
  README.md
Labels: documentation

#73 Remove '+ value' button from multi choice widget.
  trogon/widgets/parameter_controls.py
Labels: bug

#72 Do not treat Select.BLANK as a supplied value
  trogon/widgets/parameter_controls.py
Labels: bug

#14 feat: Add support for Typer
  README.md
  poetry.lock
  pyproject.toml
  trogon/typer.py
Labels: enhancement

#87 Update Python job versions to match stated compatibility
  .github/workflows/ci.yaml
Labels: enhancement
